server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/player
    username: hapeki
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-aql: true
  main:
    web-application-type: servlet

